[editor]
bufferline = "multiple"
cursorline = true
end-of-line-diagnostics = "hint"
line-number = "relative"
rulers = [80]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
character = "â•Ž"
render = true

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "disable"

[editor.lsp]
auto-signature-help = false
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[keys.insert]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
"^" = ["goto_first_nonwhitespace"]
"G" = ["goto_last_line"]
C-e = [ ":new", ":insert-output yazi", ":buffer-close!", ":redraw", ":reload-all" ]
C-g = [ ":new", ":insert-output lazygit", ":buffer-close!", ":redraw", ":reload-all" ]
# space.B = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
space.B = ":echo %sh{git show --no-patch --format='%%h (%%an: %%ar): %%s' $(git blame -p %{buffer_name} -L%{cursor_line},+1 | head -1 | cut -d' ' -f1)}"

[keys.select]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]

# [keys.normal.space.e]
# e = [ ":new", ":insert-output yazi", ":buffer-close!", ":redraw", ":reload-all" ]
# g = [ ":new", ":insert-output lazygit", ":buffer-close!", ":redraw", ":reload-all" ]
